# Generated by Django 2.2.3 on 2019-07-08 21:11

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='button_text',
            field=models.TextField(default='설교집 바로가기'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_text1',
            field=models.TextField(default='故 이용규 목사'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_text2',
            field=models.TextField(default='설교 모음집'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='paragraph1',
            field=models.TextField(default='총 42권'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='paragraph2',
            field=wagtail.core.fields.RichTextField(default='故 이용규목사 유작 ( 遺作 ) 성경강해 설교집 제 42권'),
        ),
    ]
