# Generated by Django 2.2.3 on 2019-09-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0009_theologyseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonsByScriptureSubpage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('scripture', models.TextField(default='설교 본문')),
                ('sermon_title', models.TextField(default='설교 제목')),
                ('sermon_link', models.URLField(default='https://leeyongkyu.s3-us-west-1.amazonaws.com/')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
