# Generated by Django 2.2.3 on 2019-09-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190921_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesis',
            name='sermon_number',
            field=models.IntegerField(default=1),
        ),
    ]
