# Generated by Django 2.2.3 on 2019-09-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_genesis_sermon_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genesis',
            name='sermon_number',
        ),
    ]
